export const NomeElementos = [
    'Hidrogênio', 'Hélio', 'Lítio', 'Berílio',
    'Boro', 'Carbono', 'Nitrogênio', 'Oxigênio',
    'Flúor', 'Neônio', 'Sódio', 'Magnésio',
    'Alumínio', 'Silício', 'Fósforo',
    'Enxofre', 'Cloro', 'Argônio',
    'Potássio', 'Cálcio', 'Escândio',
    'Titânio', 'Vanádio', 'Crômio',
    'Manganês', 'Ferro', 'Cobalto',
    'Níquel', 'Cobre', 'Zinco',
    'Gálio', 'Germânio', 'Arsênio',
    'Selênio', 'Bromo', 'Criptônio',
    'Rubídio', 'Estrôncio', 'Ítrio',
    'Zircônio', 'Nióbio', 'Molibdênio',
    'Tecnécio', 'Rutênio', 'Ródio',
    'Paládio', 'Prata', 'Cádmio',
    'Índio', 'Estanho', 'Antimônio',
    'Telúrio', 'Íodo', 'Xenônio',
    'Césio', 'Bário', 'Lantânio',
    'Cério', 'Praseodímix', 'Neodímio',
    'Promécio', 'Samário', 'Európio',
    'Gadolínio', 'Térbio', 'Disprósio',
    'Hólmio', 'Erbio', 'Túlio',
    'Itérbio', 'Lutécio', 'Háfnio',
    'Tântalo', 'Tungstênio', 'Rênio',
    'Ósmio', 'Irídio', 'Platina',
    'Ouro', 'Mercúrio', 'Tálio',
    'Chumbo', 'Bismuto', 'Polônio',
    'Astato', 'Radônio', 'Frâncio',
    'Rádio', 'Actínio', 'Tório',
    'Protactínio', 'Urânio', 'Neptúnio',
    'Plutônio', 'Amerício', 'Cúrio',
    'Berquélio', 'Califórnio', 'Einstênio',
    'Férmio', 'Mendelévio', 'Nobélio',
    'Laurêncio', 'Rutherfórdio', 'Dúbnio',
    'Seabórgio', 'Bóhrio', 'Hássio',
    'Meitnério', 'Darmstádio', 'Roentgênio',
    'Copernício', 'Ununtrio', 'Fleróvio',
    'Ununpentio', 'Livermório', 'Ununséptio',
    'Ununóctio'
];
