export const elementos = [{
    nome: 'Hidrogênio',
    sigla: 'H',
    massa: 1008,
    atomico: 1,
    class: 'nao_metal',
    fusao: '-259,2 °C',
    ebulicao: '-252,87 °C',
    valencia: 'possui 1 elétron (K)',
    nox: '+1',
    curiosidade: 'Encontrado em água (H2O), em estrelas (Sol) e Universo (75% do Universo é composto de hidrogênio)',
    distribuicao: '1s1',
    estado: 'Gasoso',
    familia: 'Metais Alcalinos',
    periodo: '1º Período'
},
{
    nome: 'Hélio',
    sigla: 'He',
    massa: 40026,
    atomico: 2,
    class: 'gas_nobre',
    fusao: '-272,2 °C',
    ebulicao: '-26893 °C',
    valencia: 'possui 2 elétrons (K)',
    nox: 'Não contém',
    curiosidade: 'Encontrado em estrelas (Sol), gás natural (em torno de 0,4%) e Universo (23%)',
    distribuicao: '1s2',
    estado: 'Gasoso',
    familia: 'Gáses Nobres',
    periodo: '1º Período'
},
{
    nome: 'Lítio',
    sigla: 'Li',
    massa: 694,
    atomico: 3,
    class: 'metal_alcalino',
    fusao: '180,5 °C',
    ebulicao: '1336 °C',
    valencia: 'possui 1 elétron (L)',
    nox: '+1',
    curiosidade: 'Encontrado em pequenas quantidades na comida e na água Utilizado na medicina (eficaz no controle d algumas doenças mentais e alterações de humor) e em baterias',
    distribuicao: '1s2 2s1',
    estado: 'Sólido',
    familia: 'Metais Alcalinos',
    periodo: '2º Período'
},
{
    nome: 'Berílio',
    sigla: 'Be',
    massa: 90122,
    atomico: 4,
    class: 'metal_alcalino_terroso',
    fusao: '1280 °C',
    ebulicao: '2970 °C',
    valencia: 'possui 2 elétrons (L)',
    nox: '+2',
    curiosidade: 'Usado para aumentar resistência de ligas metálicas Utilizado para produzir molas, relógios, giroscópios e reatores nucleares Esmeralda é um composto químico natural que contém berílio',
    distribuicao: '1s2 2s2',
    estado: 'Sólido',
    familia: 'Metais Alcalino Terrosos',
    periodo: '2º Período'
},
{
    nome: 'Boro',
    sigla: 'B',
    massa: 1081,
    atomico: 5,
    class: 'semi_metal',
    fusao: '2300 °C',
    ebulicao: '2580 °C',
    valencia: 'possui 3 elétrons (L)',
    nox: '+3',
    curiosidade: 'Corpo humano contém, aproximadamente, 0,00007% de Boro Usado para produção de cerâmica e vidros, na agricultura, medicamentos, etc',
    distribuicao: '1s2 2s2 2p1',
    estado: 'Sólido',
    familia: 'Família do Boro',
    periodo: '2º Período'
},
{
    nome: 'Carbono',
    sigla: 'C',
    massa: 12011,
    atomico: 6,
    class: 'nao_metal',
    fusao: '3500 °C',
    ebulicao: '4830 °C',
    valencia: 'possui 4 elétrons (L)',
    nox: '-4 -2 +2 +4',
    curiosidade: '0,5% da massa do Universo 23% da massa de um ser humano Utilizando na metalurgia para produção de aço Encontra-se na forma de grafite, em gás natural e etc',
    distribuicao: '1s2 2s2 2p2',
    estado: 'Sólido',
    familia: 'Família do Carbono',
    periodo: '2º Período'
},
{
    nome: 'Nitrogênio',
    sigla: 'N',
    massa: 14007,
    atomico: 7,
    class: 'nao_metal',
    fusao: '-210 °C',
    ebulicao: '-196 °C',
    valencia: 'possui 5 elétrons (L)',
    nox: '-3 -2 -1 +1  +5',
    curiosidade: '0,1% da massa do Universo 2,6% da massa do ser humano Presente em vários compostos orgânicos',
    distribuicao: '1s2 2s2 2p3 ',
    estado: 'Gasoso',
    familia: 'Família do Nitrogênio',
    periodo: '2º Período'
},
{
    nome: 'Oxigênio',
    sigla: 'O',
    massa: 15999,
    atomico: 8,
    class: 'nao_metal',
    fusao: '°C',
    fusao: '-222 °C',
    ebulicao: '-183 °C',
    valencia: 'possui 6 elétrons (L)',
    nox: '-2 -1 -1/2 +2',
    curiosidade: '1% da massa do Universo 86% da massa do Oceano Encontrando na superfice da Terra e em minerais Usado em soldagem, cortes de metais, instalações hospitalares para manutenção da vida e etc',
    distribuicao: '1s2 2s2 2p4',
    estado: 'Gasoso',
    familia: 'Calcogênio',
    periodo: '2º Período'
},
{
    nome: 'Flúor',
    sigla: 'F',
    massa: 18998,
    atomico: 9,
    class: 'halogenio',
    fusao: '-220 °C',
    ebulicao: '-188 °C',
    valencia: 'possui 7 elétrons (L)',
    nox: '-1',
    curiosidade: 'Encontra-se em minerais (principalmente em criolita, fluorita e fluorapatita) Utilizado no enriquecimento do urânio para usinas nucleares Utilizado em cremes dentais para diminuir a incidência de cáries',
    distribuicao: '1s2 2s2 2p5',
    estado: 'Gasoso',
    familia: 'Halogênio',
    periodo: '2º Período'
},
{
    nome: 'Neônio',
    sigla: 'Ne',
    massa: 2018,
    atomico: 10,
    class: 'gas_nobre',
    fusao: '-249 °C',
    ebulicao: '-246 °C',
    valencia: 'possui 8 elétrons (L)',
    nox: 'Não contém',
    curiosidade: '',
    distribuicao: '1s2 2s2 2p6',
    estado: 'gasoso',
    familia: 'Gáses Nobres',
    periodo: '2º Período'
},
{
    nome: 'Sódio',
    sigla: 'Na',
    massa: 2299,
    atomico: 11,
    class: 'metal_alcalino',
    fusao: '98 °C',
    ebulicao: '892 °C',
    valencia: 'possui 1 elétron (M)',
    nox: '+1',
    curiosidade: 'Encontra-se em diversos minerais, principalmente no sal comum Usado na indústria química, na cozinha (sal de cozinha), utilizado como trocador de calor em reatores nucleares',
    distribuicao: '1s2 2s2 2p6 3s1',
    estado: 'Sólido',
    familia: 'Metais Alcalinos',
    periodo: '3º Período'
},
{
    nome: 'Magnésio',
    sigla: 'Mg',
    massa: 24305,
    atomico: 12,
    class: 'metal_alcalino_terroso',
    fusao: '650 °C',
    ebulicao: '1107 °C',
    valencia: 'possui 2 elétron (M)',
    nox: '+2',
    curiosidade: 'Encontra-se em minerais como a dolomita, diópsido e etc Usado em pirotecnia, em rodas por ser leve, em sistemas de tratamento de água e etc',
    distribuicao: '1s2 2s2 2p6 3s2',
    estado: 'Sólido',
    familia: 'Metais Alcalino Terrosos',
    periodo: '3º Período'
},
{
    nome: 'Alumínio',
    sigla: 'Al',
    massa: 26982,
    atomico: 13,
    class: 'metal_representativo',
    fusao: '660 °C',
    ebulicao: '2450 °C',
    valencia: 'possui 3 elétron (M)',
    nox: '+3',
    curiosidade: 'Normalmente encontrado em minerais (óxidos e silicatos) Utilizado em utensílios de cozinha, latas e etc',
    distribuicao: '1s2 2s2 2p6 3s2 3p1',
    estado: 'Sólido',
    familia: 'Família do Boro',
    periodo: '3º Período'
},
{
    nome: 'Silício',
    sigla: 'Si',
    massa: 28085,
    atomico: 14,
    class: 'semi_metal',
    fusao: '1410 °C',
    ebulicao: '2350 °C',
    valencia: 'possui 4 elétron (M)',
    nox: '-4 +2 +4',
    curiosidade: 'Mais de 90% da crosta terrestre é de minerais a base de silicatos Utilizado em lubrificantes, sílica (dióxido de silício) é o principal ingrediente do vidro',
    distribuicao: '1s2 2s2 2p6 3s2 3p4',
    estado: 'Sólido',
    familia: 'Família do Carbono',
    periodo: '3º Período'
},
{
    nome: 'Fósforo',
    sigla: 'P',
    massa: 30974,
    atomico: 15,
    class: 'nao_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Enxofre',
    sigla: 'S',
    massa: 3206,
    atomico: 16,
    class: 'nao_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cloro',
    sigla: 'Cl',
    massa: 3545,
    atomico: 17,
    class: 'halogenio',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Argônio',
    sigla: 'Ar',
    massa: 39948,
    atomico: 18,
    class: 'gas_nobre',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Potássio',
    sigla: 'K',
    massa: 39098,
    atomico: 19,
    class: 'metal_alcalino',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cálcio',
    sigla: 'Ca',
    massa: 40078,
    atomico: 20,
    class: 'metal_alcalino_terroso',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Escândio',
    sigla: 'Sc',
    massa: 44956,
    atomico: 21,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Titânio',
    sigla: 'Ti',
    massa: 47867,
    atomico: 22,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Vanádio',
    sigla: 'V',
    massa: 50942,
    atomico: 23,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Crômio',
    sigla: 'Cr',
    massa: 51996,
    atomico: 24,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Manganês',
    sigla: 'Mn',
    massa: 54938,
    atomico: 25,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Ferro',
    sigla: 'Fe',
    massa: 55845,
    atomico: 26,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cobalto',
    sigla: 'Co',
    massa: 58933,
    atomico: 27,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Níquel',
    sigla: 'Ni',
    massa: 58693,
    atomico: 28,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cobre',
    sigla: 'Cu',
    massa: 63546,
    atomico: 29,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Zinco',
    sigla: 'Zn',
    massa: 6538,
    atomico: 30,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Gálio',
    sigla: 'Ga',
    massa: 69723,
    atomico: 31,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Germânio',
    sigla: 'Ge',
    massa: 7263,
    atomico: 32,
    class: 'semi_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Arsênio',
    sigla: 'As',
    massa: 74922,
    atomico: 33,
    class: 'semi_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Selênio',
    sigla: 'Se',
    massa: 78971,
    atomico: 34,
    class: 'nao_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Bromo',
    sigla: 'Br',
    massa: 79904,
    atomico: 35,
    class: 'halogenio',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Criptônio',
    sigla: 'Kr',
    massa: 83798,
    atomico: 36,
    class: 'gas_nobre',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Rubídio',
    sigla: 'Rb',
    massa: 85468,
    atomico: 37,
    class: 'metal_alcalino',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Estrôncio',
    sigla: 'Sr',
    massa: 8762,
    atomico: 38,
    class: 'metal_alcalino_terroso',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Ítrio',
    sigla: 'Y',
    massa: 88906,
    atomico: 39,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Zircônio',
    sigla: 'Zr',
    massa: 91224,
    atomico: 40,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Nióbio',
    sigla: 'Nb',
    massa: 92906,
    atomico: 41,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Molibdênio',
    sigla: 'Mo',
    massa: 9595,
    atomico: 42,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tecnécio',
    sigla: 'Tc',
    massa: 98,
    atomico: 43,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Rutênio',
    sigla: 'Ru',
    massa: 10107,
    atomico: 44,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Ródio',
    sigla: 'Rh',
    massa: 10291,
    atomico: 45,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Paládio',
    sigla: 'Pd',
    massa: 10642,
    atomico: 46,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Prata',
    sigla: 'Ag',
    massa: 10787,
    atomico: 47,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cádmio',
    sigla: 'Cd',
    massa: 11241,
    atomico: 48,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Índio',
    sigla: 'In',
    massa: 11482,
    atomico: 49,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Estanhos',
    sigla: 'Sn',
    massa: 11871,
    atomico: 50,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Antimônio',
    sigla: 'Sb',
    massa: 12176,
    atomico: 51,
    class: 'semi_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Telúrio',
    sigla: 'Te',
    massa: 1276,
    atomico: 52,
    class: 'semi_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Íodo',
    sigla: 'I',
    massa: 1269,
    atomico: 53,
    class: 'halogenio',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Xenônio',
    sigla: 'Xe',
    massa: 13129,
    atomico: 54,
    class: 'gas_nobre',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Césio',
    sigla: 'Cs',
    massa: 13291,
    atomico: 55,
    class: 'metal_alcalino',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Bário',
    sigla: 'Ba',
    massa: 13733,
    atomico: 56,
    class: 'metal_alcalino_terroso',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Lantânio',
    sigla: 'La',
    massa: 13891,
    atomico: 57,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cério',
    sigla: 'Ce',
    massa: 14012,
    atomico: 58,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Praseodímix',
    sigla: 'Pr',
    massa: 14091,
    atomico: 59,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Neodímio',
    sigla: 'Nd',
    massa: 14424,
    atomico: 60,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Promécio',
    sigla: 'Pm',
    massa: 145,
    atomico: 61,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Samário',
    sigla: 'Sm',
    massa: 15036,
    atomico: 62,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Európio',
    sigla: 'Eu',
    massa: 15196,
    atomico: 63,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Gadolínio',
    sigla: 'Gd',
    massa: 15725,
    atomico: 64,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Térbio',
    sigla: 'Tb',
    massa: 15893,
    atomico: 65,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Disprósio',
    sigla: 'Dy',
    massa: 1625,
    atomico: 66,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Hólmio',
    sigla: 'Ho',
    massa: 16493,
    atomico: 67,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Erbio',
    sigla: 'Er',
    massa: 16726,
    atomico: 68,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Túlio',
    sigla: 'Tm',
    massa: 16893,
    atomico: 69,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Itérbio',
    sigla: 'Yb',
    massa: 17305,
    atomico: 70,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Lutécio',
    sigla: 'Lu',
    massa: 17497,
    atomico: 71,
    class: 'lantanideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Háfnio',
    sigla: 'Hf',
    massa: 17849,
    atomico: 72,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tântalo',
    sigla: 'Ta',
    massa: 18095,
    atomico: 73,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tungstênio',
    sigla: 'W',
    massa: 18384,
    atomico: 74,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Rênio',
    sigla: 'Re',
    massa: 18621,
    atomico: 75,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Ósmio',
    sigla: 'Os',
    massa: 19023,
    atomico: 76,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Irídio',
    sigla: 'Ir',
    massa: 19222,
    atomico: 77,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Platina',
    sigla: 'Pt',
    massa: 19508,
    atomico: 78,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Ouro',
    sigla: 'Au',
    massa: 19667,
    atomico: 79,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Mercúrio',
    sigla: 'Hg',
    massa: 20059,
    atomico: 80,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tálio',
    sigla: 'Ti',
    massa: 20438,
    atomico: 81,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Chumbo',
    sigla: 'Pb',
    massa: 2072,
    atomico: 82,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Bismuto',
    sigla: 'Bi',
    massa: 20898,
    atomico: 83,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Polônios',
    sigla: 'Po',
    massa: 209,
    atomico: 84,
    class: 'semi_metal',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Astato',
    sigla: 'At',
    massa: 210,
    atomico: 85,
    class: 'halogenio',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Radônio',
    sigla: 'Rn',
    massa: 222,
    atomico: 86,
    class: 'gas_nobre',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Frâncio',
    sigla: 'Fr',
    massa: 223,
    atomico: 87,
    class: 'metal_alcalino',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Rádio',
    sigla: 'Ra',
    massa: 226,
    atomico: 88,
    class: 'metal_alcalino_terroso',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Actínio',
    sigla: 'Ac',
    massa: 227,
    atomico: 89,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tório',
    sigla: 'Th',
    massa: 23204,
    atomico: 90,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Protactínio',
    sigla: 'Pa',
    massa: 23104,
    atomico: 91,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Urânio',
    sigla: 'U',
    massa: 23803,
    atomico: 92,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Neptúnio',
    sigla: 'Np',
    massa: 237,
    atomico: 93,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Plutônio',
    sigla: 'Pu',
    massa: 244,
    atomico: 94,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Amerício',
    sigla: 'Am',
    massa: 243,
    atomico: 95,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Cúrio',
    sigla: 'Cm',
    massa: 247,
    atomico: 96,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Berquélios',
    sigla: 'Bk',
    massa: 247,
    atomico: 97,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Califórnio',
    sigla: 'Cf',
    massa: 251,
    atomico: 98,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Einstênio',
    sigla: 'Es',
    massa: 252,
    atomico: 99,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Férmio',
    sigla: 'Fm',
    massa: 257,
    atomico: 100,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Mendelévio',
    sigla: 'Md',
    massa: 258,
    atomico: 101,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Nobélio',
    sigla: 'No',
    massa: 259,
    atomico: 102,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Laurêncio',
    sigla: 'Lr',
    massa: 262,
    atomico: 103,
    class: 'actinideos',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Rutherfórdio',
    sigla: 'Rf',
    massa: 267,
    atomico: 104,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Dúbnio',
    sigla: 'Db',
    massa: 268,
    atomico: 105,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Seabórgio',
    sigla: 'Sg',
    massa: 269,
    atomico: 106,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Bóhrio',
    sigla: 'Bh',
    massa: 270,
    atomico: 107,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Hássio',
    sigla: 'Hs',
    massa: 269,
    atomico: 108,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Meitnério',
    sigla: 'Mt',
    massa: 278,
    atomico: 109,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Darmstádio',
    sigla: 'Ds',
    massa: 281,
    atomico: 110,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Roentgênio',
    sigla: 'Rg',
    massa: 281,
    atomico: 111,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Copernício',
    sigla: 'Cn',
    massa: 285,
    atomico: 112,
    class: 'metal_de_transicao',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Nihônio',
    sigla: 'Nh',
    massa: 286,
    atomico: 113,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Fleróvio',
    sigla: 'Fl',
    massa: 289,
    atomico: 114,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Moscóvio',
    sigla: 'Mc',
    massa: 288,
    atomico: 115,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Livermório',
    sigla: 'Lv',
    massa: 293,
    atomico: 116,
    class: 'metal_representativo',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Tenessino',
    sigla: 'Ts',
    massa: 294,
    atomico: 117,
    class: 'halogenio',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
},
{
    nome: 'Oganessônio',
    sigla: 'Og',
    massa: 294,
    atomico: 118,
    class: 'gas_nobre',
    fusao: '°C',
    ebulicao: '°C',
    valencia: 'possui  elétron ()',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'º Período'
}
];
