export const elementos_2 = [
    {nome: 'Berquélios', sigla: 'Bk', massa: 247, atomico: 97, class: 'actinideos' },
    {nome: 'Califórnio', sigla: 'Cf', massa: 251, atomico: 98, class: 'actinideos' },
    {nome: 'Einstênio', sigla: 'Es', massa: 252, atomico: 99, class: 'actinideos' },
    {nome: 'Férmio', sigla: 'Fm', massa: 257, atomico: 100, class: 'actinideos' },
    {nome: 'Mendelévio', sigla: 'Md', massa: 258, atomico: 101, class: 'actinideos' },
    {nome: 'Nobélio', sigla: 'No', massa: 259, atomico: 102, class: 'actinideos' },
    {nome: 'Laurêncio', sigla: 'Lr', massa: 262, atomico: 103, class: 'actinideos' },
    {nome: 'Rutherfórdio', sigla: 'Rf', massa: 267, atomico: 104, class: 'metal_de_transicao' },
    {nome: 'Dúbnio', sigla: 'Db', massa: 268, atomico: 105, class: 'metal_de_transicao' },
    {nome: 'Seabórgio', sigla: 'Sg', massa: 269, atomico: 106, class: 'metal_de_transicao' },
    {nome: 'Bóhrio', sigla: 'Bh', massa: 270, atomico: 107, class: 'metal_de_transicao' },
    {nome: 'Hássio', sigla: 'Hs', massa: 269, atomico: 108, class: 'metal_de_transicao' },
    {nome: 'Meitnério', sigla: 'Mt', massa: 278, atomico: 109, class: 'metal_de_transicao' },
    {nome: 'Darmstádio', sigla: 'Ds', massa: 281, atomico: 110, class: 'metal_de_transicao' },
    {nome: 'Roentgênio', sigla: 'Rg', massa: 281, atomico: 111, class: 'metal_de_transicao' },
    {nome: 'Copernício', sigla: 'Cn', massa: 285, atomico: 112, class: 'metal_de_transicao' },
    {nome: 'Nihônio', sigla: 'Nh', massa: 286, atomico: 113, class: 'metal_representativo' },
    {nome: 'Fleróvio', sigla: 'Fl', massa: 289, atomico: 114, class: 'metal_representativo' },
    {nome: 'Moscóvio', sigla: 'Mc', massa: 288, atomico: 115, class: 'metal_representativo' },
    {nome: 'Livermório', sigla: 'Lv', massa: 293, atomico: 116, class: 'metal_representativo' },
    {nome: 'Tenessino', sigla: 'Ts', massa: 294, atomico: 117, class: 'halogenio' },
    {nome: 'Oganessônio', sigla: 'Og', massa: 294, atomico: 118, class: 'gas_nobre' }
]
