export const elementos_detalhes_2 = [
    {nome: 'Berquélios', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Califórnio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Einstênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Férmio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Mendelévio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Nobélio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Laurêncio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Rutherfórdio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Dúbnio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Seabórgio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Bóhrio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Hássio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Meitnério', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Darmstádio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Roentgênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Copernício', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Nihônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Fleróvio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Moscóvio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Livermório', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tenessino', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Oganessônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'}
]
