export const elementos_detalhes = [
    {nome: 'Hidrogênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Hélio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Lítio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Berílio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Boro', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Carbono', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Nitrogênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Oxigênio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Flúor', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Neônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Sódio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Magnésio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Alumínio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Silício', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Fósforo', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Enxofre', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cloro', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Argônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Potássio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cálcio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Escândio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Titânio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Vanádio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Crômio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Manganês' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Ferro', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cobalto', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Níquel', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cobre', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Zinco', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Gálio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Germânio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Arsênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Selênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Bromo', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Criptônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Rubídio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Estrôncio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Ítrio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Zircônio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Nióbio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Molibdênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tecnécio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Rutênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Ródio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Paládio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Prata', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cádmio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Índio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Estanhos' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Antimônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Telúrio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Íodo', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Xenônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Césio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Bário', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Lantânio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cério', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Praseodímix', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Neodímio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Promécio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Samário', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Európio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Gadolínio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Térbio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Disprósio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Hólmio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Erbio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Túlio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Itérbio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Lutécio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Háfnio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tântalo', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tungstênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Rênio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Ósmio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Irídio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Platina', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Ouro', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Mercúrio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tálio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Chumbo', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Bismuto', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Polônios' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Astato', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Radônio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Frâncio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Rádio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Actínio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Tório', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Protactínio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Urânio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Neptúnio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Plutônio' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Amerício' , fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'},
    {nome: 'Cúrio', fusao:'fusão', ebulicao: 'ebulição',valencia:'valência', nox:'nox', curiosidade:'curiosidade', orbitais:'orbital', estado:'estado' , familia:'familia'}
];
