export const elementos = [{
    nome: 'Hidrogênio',
    sigla: 'H',
    massa: 1.008,
    atomico: 1,
    class: 'nao_metal',
    fusao: '-259,2 °C',
    ebulicao: '-252,87 °C',
    valencia: 'possui 1 elétron (K)',
    nox: '+1',
    curiosidade: 'Encontrado em água (H2O), em estrelas (Sol) e Universo (75% do Universo é composto de hidrogênio).',
    distribuicao: '1s1',
    estado: 'gasoso (Temperatura ambiente da Terra)',
    familia: 'Metal Alcalino',
    periodo: '1º Período'
},
{
    nome: 'Hélio',
    sigla: 'He',
    massa: 4.0026,
    atomico: 2,
    class: 'gas_nobre',
    fusao: '-272,2 °C',
    ebulicao: '-268.93 °C',
    valencia: 'possui 2 elétrons (K)',
    nox: 'Não contém',
    curiosidade: 'Encontrado em estrelas (Sol), gás natural (em torno de 0,4%) e Universo (23%).',
    distribuicao: '1s2',
    estado: 'gasoso (Temperatura ambiente da Terra)',
    familia: 'Gás Nobre',
    periodo: '8º Período'
},
{
    nome: 'Lítio',
    sigla: 'Li',
    massa: 6.94,
    atomico: 3,
    class: 'metal_alcalino',
    fusao: '180,5 °C',
    ebulicao: '1342 °C',
    valencia: 'possui 1 elétrons (L)',
    nox: '+1',
    curiosidade: 'Encontrado em pequenas quantidades na comida e na água. Utilizado na medicina (eficaz no controle d algumas doenças mentais e alterações de humor.) e em baterias.',
    distribuicao: '1s2 2s1',
    estado: 'sólido',
    familia: 'Metal Alcalino',
    periodo: '2º Período'
},
{
    nome: 'Berílio',
    sigla: 'Be',
    massa: 9.0122,
    atomico: 4,
    class: 'metal_alcalino_terroso',
    fusao: '1287 °C',
    ebulicao: '2469 °C',
    valencia: 'possui 2 elétrons (L)',
    nox: '+2',
    curiosidade: 'Usado para aumentar resistência de ligas metálicas. Utilizado para produzir molas, relógios, giroscópios e reatores nucleares. Esmeralda é um composto químico natural que contém berílio.',
    distribuicao: '1s2 2s2',
    estado: 'sólido',
    familia: 'Metal Alcalino Terroso',
    periodo: '2º Período'
},
{
    nome: 'Boro',
    sigla: 'B',
    massa: 10.81,
    atomico: 5,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Carbono',
    sigla: 'C',
    massa: 12.011,
    atomico: 6,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Nitrogênio',
    sigla: 'N',
    massa: 14.007,
    atomico: 7,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Oxigênio',
    sigla: 'O',
    massa: 15.999,
    atomico: 8,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Flúor',
    sigla: 'F',
    massa: 18.998,
    atomico: 9,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Neônio',
    sigla: 'Ne',
    massa: 20.18,
    atomico: 10,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Sódio',
    sigla: 'Na',
    massa: 22.99,
    atomico: 11,
    class: 'metal_alcalino',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Magnésio',
    sigla: 'Mg',
    massa: 24.305,
    atomico: 12,
    class: 'metal_alcalino_terroso',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Alumínio',
    sigla: 'Al',
    massa: 26.982,
    atomico: 13,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Silício',
    sigla: 'Si',
    massa: 28.085,
    atomico: 14,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Fósforo',
    sigla: 'P',
    massa: 30.974,
    atomico: 15,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Enxofre',
    sigla: 'S',
    massa: 32.06,
    atomico: 16,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cloro',
    sigla: 'Cl',
    massa: 35.45,
    atomico: 17,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Argônio',
    sigla: 'Ar',
    massa: 39.948,
    atomico: 18,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Potássio',
    sigla: 'K',
    massa: 39.098,
    atomico: 19,
    class: 'metal_alcalino',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cálcio',
    sigla: 'Ca',
    massa: 40.078,
    atomico: 20,
    class: 'metal_alcalino_terroso',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Escândio',
    sigla: 'Sc',
    massa: 44.956,
    atomico: 21,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Titânio',
    sigla: 'Ti',
    massa: 47.867,
    atomico: 22,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Vanádio',
    sigla: 'V',
    massa: 50.942,
    atomico: 23,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Crômio',
    sigla: 'Cr',
    massa: 51.996,
    atomico: 24,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Manganês',
    sigla: 'Mn',
    massa: 54.938,
    atomico: 25,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Ferro',
    sigla: 'Fe',
    massa: 55.845,
    atomico: 26,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cobalto',
    sigla: 'Co',
    massa: 58.933,
    atomico: 27,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Níquel',
    sigla: 'Ni',
    massa: 58.693,
    atomico: 28,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cobre',
    sigla: 'Cu',
    massa: 63.546,
    atomico: 29,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Zinco',
    sigla: 'Zn',
    massa: 65.38,
    atomico: 30,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Gálio',
    sigla: 'Ga',
    massa: 69.723,
    atomico: 31,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Germânio',
    sigla: 'Ge',
    massa: 72.63,
    atomico: 32,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Arsênio',
    sigla: 'As',
    massa: 74.922,
    atomico: 33,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Selênio',
    sigla: 'Se',
    massa: 78.971,
    atomico: 34,
    class: 'nao_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Bromo',
    sigla: 'Br',
    massa: 79.904,
    atomico: 35,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Criptônio',
    sigla: 'Kr',
    massa: 83.798,
    atomico: 36,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Rubídio',
    sigla: 'Rb',
    massa: 85.468,
    atomico: 37,
    class: 'metal_alcalino',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Estrôncio',
    sigla: 'Sr',
    massa: 87.62,
    atomico: 38,
    class: 'metal_alcalino_terroso',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Ítrio',
    sigla: 'Y',
    massa: 88.906,
    atomico: 39,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Zircônio',
    sigla: 'Zr',
    massa: 91.224,
    atomico: 40,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Nióbio',
    sigla: 'Nb',
    massa: 92.906,
    atomico: 41,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Molibdênio',
    sigla: 'Mo',
    massa: 95.95,
    atomico: 42,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tecnécio',
    sigla: 'Tc',
    massa: 98,
    atomico: 43,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Rutênio',
    sigla: 'Ru',
    massa: 101.07,
    atomico: 44,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Ródio',
    sigla: 'Rh',
    massa: 102.91,
    atomico: 45,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Paládio',
    sigla: 'Pd',
    massa: 106.42,
    atomico: 46,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Prata',
    sigla: 'Ag',
    massa: 107.87,
    atomico: 47,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cádmio',
    sigla: 'Cd',
    massa: 112.41,
    atomico: 48,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Índio',
    sigla: 'In',
    massa: 114.82,
    atomico: 49,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Estanhos',
    sigla: 'Sn',
    massa: 118.71,
    atomico: 50,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Antimônio',
    sigla: 'Sb',
    massa: 121.76,
    atomico: 51,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Telúrio',
    sigla: 'Te',
    massa: 127.6,
    atomico: 52,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Íodo',
    sigla: 'I',
    massa: 126.9,
    atomico: 53,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Xenônio',
    sigla: 'Xe',
    massa: 131.29,
    atomico: 54,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Césio',
    sigla: 'Cs',
    massa: 132.91,
    atomico: 55,
    class: 'metal_alcalino',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Bário',
    sigla: 'Ba',
    massa: 137.33,
    atomico: 56,
    class: 'metal_alcalino_terroso',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Lantânio',
    sigla: 'La',
    massa: 138.91,
    atomico: 57,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cério',
    sigla: 'Ce',
    massa: 140.12,
    atomico: 58,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Praseodímix',
    sigla: 'Pr',
    massa: 140.91,
    atomico: 59,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Neodímio',
    sigla: 'Nd',
    massa: 144.24,
    atomico: 60,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Promécio',
    sigla: 'Pm',
    massa: 145,
    atomico: 61,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Samário',
    sigla: 'Sm',
    massa: 150.36,
    atomico: 62,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Európio',
    sigla: 'Eu',
    massa: 151.96,
    atomico: 63,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Gadolínio',
    sigla: 'Gd',
    massa: 157.25,
    atomico: 64,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Térbio',
    sigla: 'Tb',
    massa: 158.93,
    atomico: 65,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Disprósio',
    sigla: 'Dy',
    massa: 162.5,
    atomico: 66,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Hólmio',
    sigla: 'Ho',
    massa: 164.93,
    atomico: 67,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Erbio',
    sigla: 'Er',
    massa: 167.26,
    atomico: 68,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Túlio',
    sigla: 'Tm',
    massa: 168.93,
    atomico: 69,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Itérbio',
    sigla: 'Yb',
    massa: 173.05,
    atomico: 70,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Lutécio',
    sigla: 'Lu',
    massa: 174.97,
    atomico: 71,
    class: 'lantanideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Háfnio',
    sigla: 'Hf',
    massa: 178.49,
    atomico: 72,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tântalo',
    sigla: 'Ta',
    massa: 180.95,
    atomico: 73,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tungstênio',
    sigla: 'W',
    massa: 183.84,
    atomico: 74,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Rênio',
    sigla: 'Re',
    massa: 186.21,
    atomico: 75,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Ósmio',
    sigla: 'Os',
    massa: 190.23,
    atomico: 76,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Irídio',
    sigla: 'Ir',
    massa: 192.22,
    atomico: 77,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Platina',
    sigla: 'Pt',
    massa: 195.08,
    atomico: 78,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Ouro',
    sigla: 'Au',
    massa: 196.67,
    atomico: 79,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Mercúrio',
    sigla: 'Hg',
    massa: 200.59,
    atomico: 80,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tálio',
    sigla: 'Ti',
    massa: 204.38,
    atomico: 81,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Chumbo',
    sigla: 'Pb',
    massa: 207.2,
    atomico: 82,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Bismuto',
    sigla: 'Bi',
    massa: 208.98,
    atomico: 83,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Polônios',
    sigla: 'Po',
    massa: 209,
    atomico: 84,
    class: 'semi_metal',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Astato',
    sigla: 'At',
    massa: 210,
    atomico: 85,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Radônio',
    sigla: 'Rn',
    massa: 222,
    atomico: 86,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Frâncio',
    sigla: 'Fr',
    massa: 223,
    atomico: 87,
    class: 'metal_alcalino',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Rádio',
    sigla: 'Ra',
    massa: 226,
    atomico: 88,
    class: 'metal_alcalino_terroso',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Actínio',
    sigla: 'Ac',
    massa: 227,
    atomico: 89,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tório',
    sigla: 'Th',
    massa: 232.04,
    atomico: 90,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Protactínio',
    sigla: 'Pa',
    massa: 231.04,
    atomico: 91,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Urânio',
    sigla: 'U',
    massa: 238.03,
    atomico: 92,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Neptúnio',
    sigla: 'Np',
    massa: 237,
    atomico: 93,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Plutônio',
    sigla: 'Pu',
    massa: 244,
    atomico: 94,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Amerício',
    sigla: 'Am',
    massa: 243,
    atomico: 95,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Cúrio',
    sigla: 'Cm',
    massa: 247,
    atomico: 96,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Berquélios',
    sigla: 'Bk',
    massa: 247,
    atomico: 97,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Califórnio',
    sigla: 'Cf',
    massa: 251,
    atomico: 98,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Einstênio',
    sigla: 'Es',
    massa: 252,
    atomico: 99,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Férmio',
    sigla: 'Fm',
    massa: 257,
    atomico: 100,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Mendelévio',
    sigla: 'Md',
    massa: 258,
    atomico: 101,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Nobélio',
    sigla: 'No',
    massa: 259,
    atomico: 102,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Laurêncio',
    sigla: 'Lr',
    massa: 262,
    atomico: 103,
    class: 'actinideos',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Rutherfórdio',
    sigla: 'Rf',
    massa: 267,
    atomico: 104,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Dúbnio',
    sigla: 'Db',
    massa: 268,
    atomico: 105,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Seabórgio',
    sigla: 'Sg',
    massa: 269,
    atomico: 106,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Bóhrio',
    sigla: 'Bh',
    massa: 270,
    atomico: 107,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Hássio',
    sigla: 'Hs',
    massa: 269,
    atomico: 108,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Meitnério',
    sigla: 'Mt',
    massa: 278,
    atomico: 109,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Darmstádio',
    sigla: 'Ds',
    massa: 281,
    atomico: 110,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Roentgênio',
    sigla: 'Rg',
    massa: 281,
    atomico: 111,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Copernício',
    sigla: 'Cn',
    massa: 285,
    atomico: 112,
    class: 'metal_de_transicao',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Nihônio',
    sigla: 'Nh',
    massa: 286,
    atomico: 113,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Fleróvio',
    sigla: 'Fl',
    massa: 289,
    atomico: 114,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Moscóvio',
    sigla: 'Mc',
    massa: 288,
    atomico: 115,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Livermório',
    sigla: 'Lv',
    massa: 293,
    atomico: 116,
    class: 'metal_representativo',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Tenessino',
    sigla: 'Ts',
    massa: 294,
    atomico: 117,
    class: 'halogenio',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
},
{
    nome: 'Oganessônio',
    sigla: 'Og',
    massa: 294,
    atomico: 118,
    class: 'gas_nobre',
    fusao: 'fusão',
    ebulicao: 'ebulição',
    valencia: 'valência',
    nox: 'nox',
    curiosidade: 'curiosidade',
    distribuicao: 'distribuição',
    estado: 'estado',
    familia: 'familia',
    periodo: 'período'
}
];
