export const cationsAnionsSigla = [
    'H', 'H30', 'Li', 'Na', 'K', 'Rb', 'Cs', 'Ag', 'NH4', 'Be',
    'Mg', 'Ca', 'Sr', 'Ba', 'Ra', 'Zn', 'Al', 'Bi', 'Cu', 'Hg',
    'Fe', 'Co', 'Ni', 'Cr', 'Au', 'Sn', 'Pb', 'Pt', 'Mn', 'Ti',
    'Cl', 'Br', 'I', 'F', 'ClO', 'ClO2', 'ClO3', 'ClO4', 'BrO', 'BrO2',
    'BrO3', 'IO', 'IO3', 'IO4', 'NO2', 'NO3', 'N3', 'NH2', 'CN', 'OCN',
    'NCO', 'SCN', 'PO3', 'H2PO2', 'MnO4', 'CH3COO', 'OH', '[Al(OH)4]',
    'H', 'O2', 'HS', 'HSO3', 'HSO4', 'HCO3', 'H2PO4', 'AlO2', 'S',
    'Se', 'SO3', 'S2O3', 'S2O4', 'S2O8', 'MnO4', 'CO3', 'MnO3',
    'SnO2', 'C2O4', 'SnO3', 'SiF6', 'PbO2', 'PbO3', 'SO4',
    'S2O7', 'HPO3', 'SiO3', 'CrO4', 'Cr2O7', 'O', 'O2', '[Zn(OH)4]',
    '[PtCl6]', 'HPO4', 'N', 'P', '[Fe(CN)6]', 'PO4', 'AsO3', 'AsO4',
    'SbO3', 'SbO4', 'BO3', '[Fe(CN)6]', 'P2O7', 'P2O6', 'SiO4'
];
export const cationsAnionsNome = [
    'Hidrogênio', 'Hidrônio', 'Lítio', 'Sódio', 'Pótassio', 'Rubídio',
    'Césio', 'Prata', 'Amônio', 'Berílio', 'Magnésio', 'Cálcio',
    'Estrôncio', 'Bário', 'Rádio', 'Zinco', 'Alumínio', 'Bismuto',
    'Cobre', 'Mercúrio', 'Ferro', 'Cobalto', 'Níquel', 'Cromo',
    'Ouro', 'Estanho', 'Chumbo', 'Platina', 'Manganês', 'Titânio',
    'Cloreto', 'Brometo', 'Iodeto', 'Fluoreto', 'Hipoclorito',
    'Clorito', 'Clorato', 'Perclorato', 'Hipobromito', 'Bromito',
    'Bromato', 'Hipoiodito', 'Iodato', 'Periodato', 'Nitrito',
    'Nitrato', 'Azoteto', 'Amideto', 'Cianeto', 'Cianato', 'Isocianato',
    'Tiocianato', 'Metafosfato', 'Hipofosfato', 'Permanganato', 'Acetato',
    'Hidróxido', 'Tetrahidroxoaluminato(3)', 'Hidreto', 'Hiperóxido',
    'Hidrogenossulfeto', 'Hidrogenossulfito', 'Hidrogenossulfato',
    'Hidrogenocarbonato', 'Diidrogenofosfato', 'Aluminato', 'Sulfeto',
    'Seleneto', 'Sulfito', 'Tiossulfato', 'Hipossulfito', 'Persulfato',
    'Manganato', 'Carbonato', 'Manganito', 'Estanito', 'Oxalato', 'Estanato',
    'Fluorsilicato', 'Plumbito', 'Plumbato', 'Sulfato', 'Pirossulfato',
    'Fosfito', 'Metassilicato', 'Cromato', 'Dicromato', 'Óxido', 'Peróxido',
    'Tetraidroxozincato(2)', 'Hexacloroplatinato(4)', 'Hidrogenofosfato',
    'Nitreto', 'Fosfeto', 'Ferricianeto', 'Fosfato', 'Arsenito', 'Arseniato',
    'Antimonito', 'Antimoniato', 'Borato', 'Ferrocianeto', 'Pirofosfato',
    'Hipofosfato', 'Ortossilicato',
];
